// End-to-end test: spins up the server on a temp DB and exercises every critical flow.
process.env.DB_FILE = 'data/test.db'; process.env.ADMIN_PASSWORD = 'adminpass123'; process.env.PORT = 0;
require('node:fs').rmSync('data/test.db', { force: true });
const server = require('./server'); const assert = require('node:assert');
let n = 0; const ok = (c, m) => { assert(c, m); console.log('  ✓', m); n++; };
(async () => {
  await new Promise(r => server.listen(0, r)); const base = 'http://127.0.0.1:' + server.address().port;
  const mk = () => { let c = ''; return async (p, m = 'GET', b) => { const r = await fetch(base + p, { method: m, headers: { ...(b ? { 'Content-Type': 'application/json' } : {}), cookie: c }, body: b && JSON.stringify(b) }); const sc = r.headers.get('set-cookie'); if (sc) c = sc.split(';')[0]; const t = await r.text(); let j; try { j = JSON.parse(t) } catch { j = t } return { s: r.status, j }; } };
  const A = mk(), U = mk(), V = mk();
  const reg = { email: 't@x.com', username: 'tester', password: 'password1', confirm: 'password1', birth_date: '2000-01-01' };
  ok((await U('/api/auth/register', 'POST', reg)).s === 200, 'register');
  ok((await U('/api/auth/register', 'POST', reg)).j.error === 'Tên tài khoản này đã được sử dụng.', 'duplicate username');
  ok((await U('/api/auth/register', 'POST', { ...reg, username: 'tester2' })).s === 409, 'duplicate email');
  const bad1 = await V('/api/auth/login', 'POST', { username: 'tester', password: 'wrong' }), bad2 = await V('/api/auth/login', 'POST', { username: 'nouser', password: 'wrong' });
  ok(bad1.j.error === bad2.j.error && bad1.s === 401, 'wrong login: identical error for bad user/pass');
  ok((await U('/api/auth/login', 'POST', { username: 'tester', password: 'password1' })).s === 200, 'login ok');
  ok((await U('/api/auth/me')).j.user.balance === 0, 'session /me, balance 0');
  ok((await V('/api/services')).s === 401, 'services need auth');
  const svc = (await U('/api/services')).j.services; ok(svc.length >= 6, 'list services');
  ok((await U(`/api/services/${svc[0].id}/purchase`, 'POST', {})).s === 402, 'buy with insufficient balance rejected');
  ok((await U('/api/admin/stats')).s === 403, 'user blocked from admin API');
  ok((await A('/api/auth/login', 'POST', { username: 'admin', password: 'adminpass123' })).s === 200, 'admin login');
  const users = (await A('/api/admin/users')).j.users, t = users.find(u => u.username === 'tester');
  ok((await A(`/api/admin/users/${t.id}/balance`, 'PATCH', { amount: 50000, reason: 'test' })).j.balance === 50000, 'admin +50000');
  ok((await A(`/api/admin/users/${t.id}/balance`, 'PATCH', { amount: -10000 })).j.balance === 40000, 'admin -10000');
  ok((await A(`/api/admin/users/${t.id}/balance`, 'PATCH', { amount: -999999 })).s === 400, 'balance cannot go negative');
  // double-purchase: 40k balance, 20k item -> exactly two of three parallel buys succeed
  const rs = await Promise.all([1, 2, 3].map(() => U(`/api/services/${svc[0].id}/purchase`, 'POST', {})));
  ok(rs.filter(r => r.s === 200).length === 2 && (await U('/api/auth/me')).j.user.balance === 0, 'concurrent purchases: no overspend');
  const o = (await U('/api/orders')).j.orders[0], d = await U(`/api/orders/${o.id}/download`);
  ok(d.s === 200 && String(d.j).includes('Placeholder'), 'download after purchase');
  ok((await V(`/api/orders/${o.id}/download`)).s === 401, 'download needs login');
  ok((await A(`/api/orders/${o.id}/download`)).s === 404, "other user's order not downloadable");
  ok((await U('/api/recharge', 'POST', { provider: 'VIETTEL', amount: 20000, serial: '12345678901', card_code: '98765432101' })).s === 200, 'recharge request created');
  ok((await U('/api/auth/me')).j.user.balance === 0, 'no auto-credit on submit');
  const rq = (await A('/api/admin/recharge')).j.items[0];
  ok((await A(`/api/admin/recharge/${rq.id}/approve`, 'PATCH', {})).s === 200 && (await U('/api/auth/me')).j.user.balance === 20000, 'approve credits balance');
  ok((await A(`/api/admin/recharge/${rq.id}/approve`, 'PATCH', {})).s === 409, 'cannot approve twice');
  await U('/api/recharge', 'POST', { provider: 'VIETTEL', amount: 10000, serial: '12345678902', card_code: '98765432102' });
  const rq2 = (await A('/api/admin/recharge')).j.items[0];
  ok((await A(`/api/admin/recharge/${rq2.id}/reject`, 'PATCH', {})).s === 200 && (await U('/api/auth/me')).j.user.balance === 20000, 'reject leaves balance');
  ok((await A('/api/admin/services', 'POST', { name: 'NEW', category: 'bot', description: 'x', price: 5000, file: '../../server.js' })).s === 200, 'admin add service');
  const nw = (await A('/api/services')).j.services.find(s => s.name === 'NEW');
  ok((await A(`/api/admin/services/${nw.id}`, 'PATCH', { ...nw, price: 7000 })).s === 200 && (await A('/api/services')).j.services.find(s => s.id === nw.id).price === 7000, 'admin change price');
  await U(`/api/services/${nw.id}/purchase`, 'POST', {}); const no = (await U('/api/orders')).j.orders[0];
  ok((await U(`/api/orders/${no.id}/download`)).s === 404, 'path traversal in file name blocked');
  ok((await U('/api/account/change-password', 'POST', { old_password: 'password1', new_password: 'newpassword2' })).s === 200, 'change password');
  ok((await U('/api/auth/logout', 'POST', {})).s === 200 && (await U('/api/auth/me')).s === 401, 'logout kills session');
  ok((await fetch(base + '/files/dichvu/botzalo20k.zip')).status === 404, 'files/ not publicly served');
  ok((await fetch(base + '/data/kwihh.db')).status === 404, 'database not exposed');
  console.log(`\nALL ${n} CHECKS PASSED`); server.close(); process.exit(0);
})().catch(e => { console.error('FAIL', e); process.exit(1); });
